### ISSUE TITLE
关于statusid

### ISSUE THREAD

**Issue by zchan0** [Anthonyeef/FanfouDailyApiDoc#1]
哈喽意粉同学，
我看了下`statusid`作为

> 该条饭否的唯一id

它的使用方式应该是
`fanfou.com/statuses/statusid`
或者
`m.fanfou.com/statuses/statusid`

之前说的第三方分享的问题就解决啦

**Comment by Anthonyeef** [comment]
Z 姐好赞！！感恩～
Many thanks for this : )
